version: '3.8'

services:
  # Laravel application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_DATABASE=uzapoint
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8000:9000" # Maps port 9000 inside the container to port 8000 on the host machine
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - db

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: uzapoint
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306" # Exposes the MySQL port to the host machine
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "8080:80" # Maps port 80 inside the container to port 8080 on the host machine
    depends_on:
      - db
    networks:
      - laravel_network
# Volumes for data persistence
volumes:
  db_data:

# Custom network for the application
networks:
  laravel_network:
    driver: bridge
